version: '3.8'

services:
  db:
    image: postgres:15
    container_name: rm_traceability_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: rm_saas_user
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: rastreabilidade_saas
      POSTGRES_INITDB_ARGS: "--auth-host md5 --auth-local md5"
    ports:
      - "5433:5432"  # Host:5433 -> Container:5432
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - rm_traceability_network

  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: rm_traceability_app
    restart: unless-stopped
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USERNAME: rm_saas_user
      DB_PASSWORD: password123
      DB_NAME: rastreabilidade_saas
      JWT_SECRET: RmS@as2025!SecureJWTSecret
      APP_SECRET: dc55cd2760e51f279b2fdb66da91436d
      APP_PORT: 3001
      NODE_ENV: development
    ports:
      - "3001:3001"        # Mapeia a porta 3001 do host -> container
    depends_on:
      - db
    networks:
      - rm_traceability_network
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - .env

volumes:
  db_data:

networks:
  rm_traceability_network:
    driver: bridge
